<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-UCGO14RO" ignored="2" name="Default test(failed)" tests="2" failures="2" timestamp="12 Mar 2021 10:48:17 GMT" time="0.047" errors="0">
  <testcase name="tc2" time="0.016" classname="org.rerun.TestCases">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.rerun.TestCases.tc2(TestCases.java:17)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- tc2 -->
  <testcase name="tc3" time="0.0" classname="org.rerun.TestCases">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.rerun.TestCases.tc3(TestCases.java:24)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- tc3 -->
  <testcase name="tc1" time="0.0" classname="org.rerun.TestCases">
    <ignored/>
  </testcase> <!-- tc1 -->
  <testcase name="tc4" time="0.0" classname="org.rerun.TestCases">
    <ignored/>
  </testcase> <!-- tc4 -->
</testsuite> <!-- Default test(failed) -->
